name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
  
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_display: large

         # Plugins - Add multiple metrics

          
          plugin_repositories_forks: yes
          plugin_repositories_affiliations: owner,organization_member,collaborator
        
          #plugin_achievements: yes
          #plugin_achievements_only: >-
          #   polyglot, stargazer, sponsor, deployer, member, maintainer, developer,
          #  scripter, packager, explorer, infographile, manager
          #plugin_achievements_display: compact
          #plugin_achievements_threshold: C
        
          #plugin_isocalendar: yes
          #plugin_isocalendar_duration: full-year
        
          plugin_languages: yes
          plugin_languages_sections: recently-used
          #plugin_languages_recent_load: 1000  # Increased to capture more data
          #plugin_languages_recent_days: 14   
          #plugin_languages_ignored: HTML,CSS,JavaScript
          #plugin_languages_indepth: yes
          #plugin_languages_other: yes
          #plugin_languages_details: percentage

          

          
          

         
