name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

         # Plugins - Add multiple metrics
          repositories_forks: yes
          repositories_affiliations: owner, collaborator, organization_member
          plugin_languages: yes
          plugin_languages_sections: recently-used
          plugin_languages_recent_load: 400
          plugin_languages_recent_days: 14
          plugin_followup: yes
          plugin_followup_sections: user
          plugin_reactions: yes
          plugin_habits: yes
          plugin_habits_from: 1000
          plugin_habits_days: 30
          plugin_lines: yes
          plugin_topics: yes
          plugin_topics_limit: 15
          plugin_stargazers: yes
          plugin_stargazers_charts_type: classic
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_notable: yes
          plugin_achievements: yes
          plugin_achievements_only: >-
              polyglot, stargazer, sponsor, deployer, member, maintainer, developer,
              scripter, packager, explorer, infographile, manager
          plugin_achievements_display: compact
          plugin_achievements_threshold: X
